#!/usr/bin/env python3
"""
azure-nsg-example.py

Generate or apply Azure NSG egress rules for Databricks IP ranges.
Wraps extract-databricks-ips.py and outputs either:

  az-cli    -- az network nsg rule create commands (preview or --apply to execute)
  terraform -- azurerm_network_security_rule resource blocks

CIDRs are split into chunks of 50 per rule to stay within Azure NSG limits.
Each chunk gets an incrementing priority (e.g. 200, 201, ...).
Port: 443/Tcp outbound only.

Usage:
  # Preview az-cli commands (default, no changes made)
  python azure-nsg-example.py --region westus2 --nsg-name my-nsg --resource-group my-rg

  # Apply rules directly via az-cli
  python azure-nsg-example.py --region westus2 --nsg-name my-nsg --resource-group my-rg --apply

  # Output Terraform snippet
  python azure-nsg-example.py --region westus2 --format terraform

  # Custom rule name and starting priority
  python azure-nsg-example.py --region eastus --nsg-name my-nsg --resource-group my-rg \\
      --rule-name DatabricksEgress --priority 200 --apply
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

CHUNK_SIZE = 50
EXTRACTOR = Path(__file__).parent / "extract-databricks-ips.py"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def get_cidrs(region, type_filter="outbound"):
    """Fetch Databricks IP ranges for Azure via extract-databricks-ips.py."""
    cmd = [
        sys.executable, str(EXTRACTOR),
        "--cloud", "azure",
        "--region", region,
        "--type", type_filter,
        "--format", "json",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error fetching CIDRs:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    entries = json.loads(result.stdout)
    return sorted(set(e["cidr"] for e in entries if e.get("cidr")))


def chunk_cidrs(cidrs, size=CHUNK_SIZE):
    return [cidrs[i:i + size] for i in range(0, len(cidrs), size)]


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_terraform(cidrs, rule_name, priority, nsg_name, resource_group):
    """Return Terraform azurerm_network_security_rule blocks as a string."""
    chunks = chunk_cidrs(cidrs)
    nsg_ref = f'"{nsg_name}"' if nsg_name else "var.nsg_name"
    rg_ref  = f'"{resource_group}"' if resource_group else "var.resource_group_name"

    blocks = [
        "# Generated by azure-nsg-example.py",
        f"# {len(cidrs)} destination prefixes across {len(chunks)} rule(s) (chunk size: {CHUNK_SIZE})",
        "",
    ]

    for idx, chunk in enumerate(chunks, 1):
        res_suffix  = f"_part{idx}" if len(chunks) > 1 else ""
        name_suffix = f"-part{idx}" if len(chunks) > 1 else ""
        cidr_lines  = ",\n    ".join(f'"{c}"' for c in chunk)

        blocks.append("\n".join([
            f'resource "azurerm_network_security_rule" "{rule_name.lower().replace("-", "_")}{res_suffix}" {{',
            f'  name                         = "{rule_name}{name_suffix}"',
            f'  priority                     = {priority + idx - 1}',
            f'  direction                    = "Outbound"',
            f'  access                       = "Allow"',
            f'  protocol                     = "Tcp"',
            f'  source_port_range            = "*"',
            f'  destination_port_range       = "443"',
            f'  source_address_prefix        = "*"',
            f'  destination_address_prefixes = [',
            f'    {cidr_lines}',
            f'  ]',
            f'  resource_group_name          = {rg_ref}',
            f'  network_security_group_name  = {nsg_ref}',
            f'}}',
        ]))

    return "\n\n".join(blocks)


def render_azcli(cidrs, rule_name, priority, nsg_name, resource_group):
    """Return az network nsg rule create commands as a string."""
    chunks = chunk_cidrs(cidrs)
    nsg = nsg_name or "<NSG_NAME>"
    rg  = resource_group or "<RESOURCE_GROUP>"

    lines = [
        "# Generated by azure-nsg-example.py",
        f"# {len(cidrs)} destination prefixes across {len(chunks)} rule(s) (chunk size: {CHUNK_SIZE})",
        "",
    ]

    for idx, chunk in enumerate(chunks, 1):
        name_suffix = f"-part{idx}" if len(chunks) > 1 else ""
        prefixes    = " \\\n    ".join(chunk)

        lines.append("\n".join([
            "az network nsg rule create \\",
            f"  --resource-group {rg} \\",
            f"  --nsg-name {nsg} \\",
            f"  --name {rule_name}{name_suffix} \\",
            f"  --priority {priority + idx - 1} \\",
            f"  --direction Outbound \\",
            f"  --access Allow \\",
            f"  --protocol Tcp \\",
            f"  --source-address-prefixes '*' \\",
            f"  --source-port-ranges '*' \\",
            f"  --destination-port-ranges 443 \\",
            f"  --destination-address-prefixes \\",
            f"    {prefixes}",
        ]))

    return "\n\n".join(lines)


# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

def apply_azcli(cidrs, rule_name, priority, nsg_name, resource_group):
    """Execute az network nsg rule create for each chunk."""
    chunks = chunk_cidrs(cidrs)
    print(f"Applying {len(chunks)} rule(s) to NSG '{nsg_name}' in '{resource_group}'...\n")

    for idx, chunk in enumerate(chunks, 1):
        name_suffix    = f"-part{idx}" if len(chunks) > 1 else ""
        full_rule_name = f"{rule_name}{name_suffix}"
        rule_priority  = priority + idx - 1

        print(f"  [{idx}/{len(chunks)}] {full_rule_name}  priority={rule_priority}  CIDRs={len(chunk)} ... ",
              end="", flush=True)

        cmd = [
            "az", "network", "nsg", "rule", "create",
            "--resource-group", resource_group,
            "--nsg-name", nsg_name,
            "--name", full_rule_name,
            "--priority", str(rule_priority),
            "--direction", "Outbound",
            "--access", "Allow",
            "--protocol", "Tcp",
            "--source-address-prefixes", "*",
            "--source-port-ranges", "*",
            "--destination-port-ranges", "443",
            "--destination-address-prefixes", *chunk,
            "--output", "none",
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print("OK")
        else:
            print("FAILED")
            print(f"\n  Error: {result.stderr.strip()}", file=sys.stderr)
            sys.exit(1)

    print(f"\nDone. {len(chunks)} rule(s) created successfully.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate or apply Azure NSG egress rules for Databricks IP ranges",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Dry-run: preview az-cli commands (no changes made)
  %(prog)s --region westus2 --nsg-name my-nsg --resource-group my-rg

  # Apply rules directly
  %(prog)s --region westus2 --nsg-name my-nsg --resource-group my-rg --apply

  # Output Terraform HCL snippet
  %(prog)s --region westus2 --format terraform

  # Save Terraform snippet to file
  %(prog)s --region westus2 --format terraform > databricks-nsg-rules.tf

  # Custom rule name and starting priority
  %(prog)s --region eastus --nsg-name my-nsg --resource-group my-rg \\
      --rule-name DatabricksEgress --priority 200 --apply
        """,
    )

    parser.add_argument("--region", "-r", required=True,
                        help="Azure region (e.g. westus2, eastus)")
    parser.add_argument("--nsg-name",
                        help="NSG resource name (required for --apply)")
    parser.add_argument("--resource-group", "--rg",
                        help="Resource group name (required for --apply)")
    parser.add_argument("--priority", type=int, default=100,
                        help="Starting rule priority (default: 100)")
    parser.add_argument("--rule-name", default="AllowDatabricksOutbound",
                        help="Rule name prefix (default: AllowDatabricksOutbound)")
    parser.add_argument("--format", choices=["az-cli", "terraform"], default="az-cli",
                        help="Output format (default: az-cli)")
    parser.add_argument("--type", default="outbound",
                        choices=["inbound", "outbound", "all"],
                        dest="type_filter",
                        help="IP range direction to filter (default: outbound)")

    action = parser.add_mutually_exclusive_group()
    action.add_argument("--dry-run", action="store_true",
                        help="Print commands without executing (default for az-cli format)")
    action.add_argument("--apply", action="store_true",
                        help="Execute az-cli commands directly (az-cli format only)")

    args = parser.parse_args()

    # Validation
    if args.apply and args.format == "terraform":
        parser.error("--apply is only valid with --format az-cli")

    if args.apply and (not args.nsg_name or not args.resource_group):
        parser.error("--apply requires --nsg-name and --resource-group")

    # Fetch CIDRs
    print(f"Fetching Databricks IP ranges: region={args.region} type={args.type_filter} ...",
          file=sys.stderr)
    cidrs = get_cidrs(args.region, type_filter=args.type_filter)

    if not cidrs:
        print(f"No CIDRs found for region={args.region} type={args.type_filter}", file=sys.stderr)
        sys.exit(1)

    chunks = chunk_cidrs(cidrs)
    print(f"Found {len(cidrs)} CIDRs -> {len(chunks)} rule(s), "
          f"priorities {args.priority}-{args.priority + len(chunks) - 1}",
          file=sys.stderr)

    # Dispatch
    if args.apply:
        apply_azcli(cidrs, args.rule_name, args.priority, args.nsg_name, args.resource_group)

    elif args.format == "terraform":
        print(render_terraform(cidrs, args.rule_name, args.priority,
                               args.nsg_name, args.resource_group))

    else:
        # az-cli dry-run (default)
        print(render_azcli(cidrs, args.rule_name, args.priority,
                           args.nsg_name, args.resource_group))


if __name__ == "__main__":
    main()
